"""add_master_password_hash_and_tattoo_projects

Revision ID: 2fb8e778874a
Revises: 4781c60447fc
Create Date: 2026-08-30 20:10:08.137692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2fb8e778874a'
down_revision: Union[str, Sequence[str], None] = '4781c60447fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tattoo_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=64), nullable=False),
    sa.Column('complexity', sa.String(length=64), nullable=False),
    sa.Column('placement', sa.String(length=256), nullable=False),
    sa.Column('session_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('planned', 'in_progress', 'completed', 'cancelled', name='tattooprojectstatus'), nullable=False),
    sa.Column('google_event_id', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['master_id'], ['masters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tattoo_projects_business_id'), 'tattoo_projects', ['business_id'], unique=False)
    op.create_index(op.f('ix_tattoo_projects_master_id'), 'tattoo_projects', ['master_id'], unique=False)
    op.drop_index(op.f('ix_booking_chat_messages_booking_id'), table_name='booking_chat_messages')
    op.drop_table('booking_chat_messages')
    op.drop_table('payments')
    op.drop_index(op.f('ix_ai_conversations_business_id'), table_name='ai_conversations')
    op.drop_index(op.f('ix_ai_messages_conversation_id'), table_name='ai_messages')
    op.alter_column('bookings', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.drop_constraint(op.f('bookings_slot_id_key'), 'bookings', type_='unique')
    op.drop_column('businesses', 'freedom_pay_secret_key')
    op.drop_column('businesses', 'freedom_pay_merchant_id')
    op.add_column('masters', sa.Column('password_hash', sa.String(length=256), nullable=True))
    op.alter_column('services', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_column('services', 'prepayment_percent')
    op.drop_column('services', 'cancel_deadline_hours')
    op.drop_column('services', 'service_type')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_telegram_id_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_telegram_id_key'), 'users', ['telegram_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.add_column('services', sa.Column('service_type', postgresql.ENUM('appointment', 'project', name='servicetype'), autoincrement=False, nullable=False))
    op.add_column('services', sa.Column('cancel_deadline_hours', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=False))
    op.add_column('services', sa.Column('prepayment_percent', sa.INTEGER(), server_default=sa.text('50'), autoincrement=False, nullable=False))
    op.alter_column('services', 'price',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('masters', 'password_hash')
    op.add_column('businesses', sa.Column('freedom_pay_merchant_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('businesses', sa.Column('freedom_pay_secret_key', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('bookings_slot_id_key'), 'bookings', ['slot_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('bookings', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.create_index(op.f('ix_ai_messages_conversation_id'), 'ai_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_conversations_business_id'), 'ai_conversations', ['business_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'paid', 'refunded', 'failed', 'forfeited', name='paymentstatus'), server_default=sa.text("'pending'::paymentstatus"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('paid_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('gateway_order_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('gateway', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('payments_booking_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('payments_pkey')),
    sa.UniqueConstraint('booking_id', name=op.f('payments_booking_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('gateway_order_id', name=op.f('payments_gateway_order_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('booking_chat_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sender_type', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('booking_chat_messages_booking_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('booking_chat_messages_pkey'))
    )
    op.create_index(op.f('ix_booking_chat_messages_booking_id'), 'booking_chat_messages', ['booking_id'], unique=False)
    op.drop_index(op.f('ix_tattoo_projects_master_id'), table_name='tattoo_projects')
    op.drop_index(op.f('ix_tattoo_projects_business_id'), table_name='tattoo_projects')
    op.drop_table('tattoo_projects')
    # ### end Alembic commands ###
